model_name: FetalCLIP
task: segmentation
data_dir: "data/acouslic-ai"
experiment_logs_dir: "experiment_logs"
fetalclip_config_path: "FetalCLIP_config.json"
fetalclip_weights_path: "FetalCLIP_weights.pt"

num_workers: 16
batch_size: 64
max_epochs: 5
num_trials: 5

store_embeddings: true