model_name: FetalCLIP
task: segmentation
data_dir: "data/acouslic-ai"
output_dir: "outputs"
fetalclip_config_path: "FetalCLIP_config.json"
fetalclip_weights_path: "FetalCLIP_weights.pt"

num_workers: 8
batch_size: 64
max_epochs: 10
num_trials: 5

store_embeddings: true
use_augmentation: true
freeze_encoder: false